export const SET_PIE_CHART_VALUE = 'SET_PIE_CHART_VALUE'
export const SET_PIE_CHART_VALUE_SUCCESS = 'SET_PIE_CHART_VALUE_SUCCESS'
export const SET_PIE_CHART_VALUE_FAILURE = 'SET_PIE_CHART_VALUE_FAILURE'

export const SET_THEME_COLOR = 'SET_THEME_COLOR'
export const SET_THEME_COLOR_SUCCESS = 'SET_THEME_COLOR_SUCCESS'
export const SET_THEME_COLOR_FAILURE = 'SET_THEME_COLOR_FAILURE'

export const CLOCK_1S_TICK = 'CLOCK_1S_TICK'