export const GET_PIE_CHART_VALUE = 'GET_PIE_CHART_VALUE'
export const SET_PIE_CHART_VALUE = 'SET_PIE_CHART_VALUE'
export const SET_PIE_CHART_VALUE_SUCCESS = 'SET_PIE_CHART_VALUE_SUCCESS'
export const SET_PIE_CHART_VALUE_FAILURE = 'SET_PIE_CHART_VALUE_FAILURE'