export const SET_PIE_CHART_VALUE = 'SET_PIE_CHART_VALUE'
export const SET_PIE_CHART_VALUE_SUCCESS = 'SET_PIE_CHART_VALUE_SUCCESS'
export const SET_PIE_CHART_VALUE_FAILURE = 'SET_PIE_CHART_VALUE_FAILURE'

export const CLOCK_1S_TICK = 'CLOCK_1S_TICK'